language: python
python:
  - "2.7"

env:
  global:
    - SECRET_KEY=blajblajbasdf
  matrix:
    - DJANGO=1.4
    - DJANGO=1.5

install:
  - pip install -r requirements.txt --use-mirrors

script: python manage.py test classphoto groups mail sequence signup unsubscribe

notifications:
  email:
    on_success: change
    on_failure: change
